# Generated by Django 4.1.11 on 2023-10-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='ishantcollection',
        ),
    ]
